extends: airbnb
parser: babel-eslint
rules:
  no-var: 1
  prefer-arrow-callback: 1
  space-before-function-paren: 1
  object-curly-spacing: 1
  no-unused-vars: 1
  react/prop-types: 1
  max-len:
    - 1
    - 100
  vars-on-top: 1
  spaced-comment: 1
  prefer-const: 1
  object-shorthand: 1
  no-irregular-whitespace: 1
  no-else-return: 1
  no-param-reassign: 1
  arrow-body-style: 1
  comma-dangle: 1
  prefer-template: 1
  react/sort-comp: 1
  no-fallthrough: 1
  semi: 1
  react/jsx-no-bind: 1
  eqeqeq:
    - 1
    - smart
  react/jsx-closing-bracket-location:
    - 1
    - after-props
  react/jsx-indent:
    - 1
    - 2
  no-loop-func: 0
